import { Image } from "./Gallery";

export type TabContent = {
    label: string;
    images: Image[];
  };

export const tabContents: TabContent[] = [
    { label: 'ARHITECTURĂ', images: [
        { id: 11, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg',alt: 'Image 11' },
        { id: 12, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 12' },
        { id: 13, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 13' },
        { id: 14, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 14' },
        { id: 15, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 15' },
        { id: 16, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 16' },
        { id: 17, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 17' },
        { id: 18, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 18' },
        { id: 19, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 19' },
        { id: 110, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 110' },
        { id: 111, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 111' },
        { id: 112, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 112' },
        { id: 113, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 113' },
        { id: 114, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 114' },
        { id: 115, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 115' },
        { id: 116, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 116' },
        { id: 117, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 117' },
        { id: 118, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 118' },
        { id: 119, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 119' },
    ]},
    { label: 'DESIGN INTERIOR', images: [
        { id: 21, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_adara_cheles.jpg', alt: 'Image 21' },
        { id: 22, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 22' },
        { id: 23, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 23' },
        { id: 24, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 24' },
        { id: 25, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 25' },
        { id: 26, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 26' },
        { id: 27, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 27' },
        { id: 28, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 28' },
        { id: 29, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 29' },
        { id: 210, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 210' },
        { id: 211, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 211' },
        { id: 212, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 212' },
        { id: 213, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 213' },
        { id: 214, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 214' },
        { id: 215, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 215' },
        { id: 216, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 216' },
        { id: 217, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 217' },
        { id: 218, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 218' },
    ]},
    { label: 'FASHION DESIGN', images: [
        { id: 31, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 31' },
        { id: 32, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_adara_cheles.jpg', alt: 'Image 32' },
        { id: 33, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 33' },
        { id: 34, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 34' },
        { id: 35, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 35' },
        { id: 36, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 36' },
        { id: 37, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 37' },
        { id: 38, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 38' },
        { id: 39, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 39' },
        { id: 310, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 310' },
        { id: 311, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 311' },
        { id: 312, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 312' },
        { id: 313, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 313' },
        { id: 314, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 314' },
        { id: 315, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 315' },
        { id: 316, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 316' },
        { id: 317, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 317' },
        { id: 318, src: '/team_adriana_tomeci.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 318' },
    ]},
    { label: 'GAME DESIGN', images: [
        { id: 41, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 41' }, 
        { id: 42, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 42' }, 
        { id: 43, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 43' },
        { id: 44, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 44' },
        { id: 45, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_adriana_tomeci.jpg', alt: 'Image 45' },
        { id: 46, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 46' },
        { id: 47, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 47' },
        { id: 48, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 48' },
        { id: 49, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 49' },
        { id: 410, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 410' },
        { id: 411, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 411' },
        { id: 412, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 412' },
        { id: 413, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 413' },
        { id: 414, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 414' },
        { id: 415, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 415' },
        { id: 416, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 416' },
        { id: 417, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 417' },
        { id: 418, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 418' },
        { id: 419, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 419' },
        { id: 420, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 420' },
    ]},
    { label: 'SCENOGRAFIE', images: [
        { id: 51, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 51' }, 
        { id: 52, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 52' }, 
        { id: 53, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 53' },
        { id: 54, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 54' },
        { id: 55, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 55' },
        { id: 56, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 56' },
        { id: 57, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 57' },
        { id: 58, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 58' },
        { id: 59, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 59' },
        { id: 510, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 510' },
        { id: 511, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 511' },
        { id: 512, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 512' },
        { id: 513, src: '/team_cristina_stanescu.jpg', thumbnailSrc: './team_victor_stanescu.jpg', alt: 'Image 513' },
    ]},
  ];